// Auto-generated by scripts/build_intent_vocabulary.py
// DO NOT EDIT MANUALLY

export const GENERATED_INTENT_VOCAB = {
  "fetchedAt": "2025-11-09T22:36:02.330Z",
  "countries": {
    "Afghanistan": [
      "afghanistan"
    ],
    "Aland Islands": [
      "aland islands"
    ],
    "Albania": [
      "albania"
    ],
    "Algeria": [
      "algeria"
    ],
    "American Samoa": [
      "american samoa"
    ],
    "Andorra": [
      "andorra"
    ],
    "Angola": [
      "angola"
    ],
    "Anguilla": [
      "anguilla"
    ],
    "Antarctica": [
      "antarctica"
    ],
    "Antigua And Barbuda": [
      "antigua and barbuda"
    ],
    "Argentina": [
      "argentina"
    ],
    "Armenia": [
      "armenia"
    ],
    "Aruba": [
      "aruba"
    ],
    "Ascension And Tristan Da Cunha Saint Helena": [
      "ascension and tristan da cunha saint helena"
    ],
    "Australia": [
      "australia"
    ],
    "Austria": [
      "austria"
    ],
    "Azerbaijan": [
      "azerbaijan"
    ],
    "Bahrain": [
      "bahrain"
    ],
    "Bangladesh": [
      "bangladesh"
    ],
    "Barbados": [
      "barbados"
    ],
    "Belarus": [
      "belarus"
    ],
    "Belgium": [
      "belgium"
    ],
    "Belize": [
      "belize"
    ],
    "Benin": [
      "benin"
    ],
    "Bermuda": [
      "bermuda"
    ],
    "Bhutan": [
      "bhutan"
    ],
    "Bolivarian Republic Of Venezuela": [
      "bolivarian republic of venezuela"
    ],
    "Bolivia": [
      "bolivia"
    ],
    "Bonaire": [
      "bonaire"
    ],
    "Bosnia And Herzegovina": [
      "bosnia and herzegovina"
    ],
    "Botswana": [
      "botswana"
    ],
    "Brazil": [
      "brazil"
    ],
    "British Indian Ocean Territory": [
      "british indian ocean territory"
    ],
    "British Virgin Islands": [
      "british virgin islands"
    ],
    "Brunei Darussalam": [
      "brunei darussalam"
    ],
    "Bulgaria": [
      "bulgaria"
    ],
    "Burkina Faso": [
      "burkina faso"
    ],
    "Burundi": [
      "burundi"
    ],
    "Cabo Verde": [
      "cabo verde"
    ],
    "Cambodia": [
      "cambodia"
    ],
    "Cameroon": [
      "cameroon"
    ],
    "Canada": [
      "canada"
    ],
    "Chad": [
      "chad"
    ],
    "Chile": [
      "chile"
    ],
    "China": [
      "china"
    ],
    "Christmas Island": [
      "christmas island"
    ],
    "Colombia": [
      "colombia"
    ],
    "Costa Rica": [
      "costa rica"
    ],
    "Coted Ivoire": [
      "coted ivoire"
    ],
    "Croatia": [
      "croatia"
    ],
    "Cuba": [
      "cuba"
    ],
    "Curacao": [
      "curacao"
    ],
    "Cyprus": [
      "cyprus"
    ],
    "Czechia": [
      "czechia"
    ],
    "Denmark": [
      "denmark"
    ],
    "Djibouti": [
      "djibouti"
    ],
    "Dominica": [
      "dominica"
    ],
    "Dr Congo": [
      "democratic republic of the congo",
      "drc"
    ],
    "Ecuador": [
      "ecuador"
    ],
    "Egypt": [
      "egypt"
    ],
    "El Salvador": [
      "el salvador"
    ],
    "Equatorial Guinea": [
      "equatorial guinea"
    ],
    "Eritrea": [
      "eritrea"
    ],
    "Estonia": [
      "estonia"
    ],
    "Eswatini": [
      "eswatini"
    ],
    "Ethiopia": [
      "ethiopia"
    ],
    "Federated States Of Micronesia": [
      "federated states of micronesia"
    ],
    "Fiji": [
      "fiji"
    ],
    "Finland": [
      "finland"
    ],
    "France": [
      "france"
    ],
    "French Guiana": [
      "french guiana"
    ],
    "French Polynesia": [
      "french polynesia"
    ],
    "Gabon": [
      "gabon"
    ],
    "Georgia": [
      "georgia"
    ],
    "Germany": [
      "germany"
    ],
    "Ghana": [
      "ghana"
    ],
    "Gibraltar": [
      "gibraltar"
    ],
    "Greece": [
      "greece"
    ],
    "Greenland": [
      "greenland"
    ],
    "Grenada": [
      "grenada"
    ],
    "Guadeloupe": [
      "guadeloupe"
    ],
    "Guam": [
      "guam"
    ],
    "Guatemala": [
      "guatemala"
    ],
    "Guernsey": [
      "guernsey"
    ],
    "Guinea": [
      "guinea"
    ],
    "Guinea Bissau": [
      "guinea bissau"
    ],
    "Guyana": [
      "guyana"
    ],
    "Haiti": [
      "haiti"
    ],
    "Honduras": [
      "honduras"
    ],
    "Hong Kong": [
      "hong kong"
    ],
    "Hungary": [
      "hungary"
    ],
    "Iceland": [
      "iceland"
    ],
    "India": [
      "india"
    ],
    "Indonesia": [
      "indonesia"
    ],
    "Iraq": [
      "iraq"
    ],
    "Ireland": [
      "ireland"
    ],
    "Islamic Republic Of Iran": [
      "islamic republic of iran"
    ],
    "Isle Of Man": [
      "isle of man"
    ],
    "Israel": [
      "israel"
    ],
    "Italy": [
      "italy"
    ],
    "Jamaica": [
      "jamaica"
    ],
    "Japan": [
      "japan"
    ],
    "Jordan": [
      "jordan"
    ],
    "Kazakhstan": [
      "kazakhstan"
    ],
    "Kenya": [
      "kenya"
    ],
    "Kiribati": [
      "kiribati"
    ],
    "Kosovo": [
      "kosovo"
    ],
    "Kuwait": [
      "kuwait"
    ],
    "Kyrgyzstan": [
      "kyrgyzstan"
    ],
    "Latvia": [
      "latvia"
    ],
    "Lebanon": [
      "lebanon"
    ],
    "Lesotho": [
      "lesotho"
    ],
    "Liberia": [
      "liberia"
    ],
    "Libya": [
      "libya"
    ],
    "Liechtenstein": [
      "liechtenstein"
    ],
    "Lithuania": [
      "lithuania"
    ],
    "Luxembourg": [
      "luxembourg"
    ],
    "Macao": [
      "macao"
    ],
    "Madagascar": [
      "madagascar"
    ],
    "Malawi": [
      "malawi"
    ],
    "Malaysia": [
      "malaysia"
    ],
    "Maldives": [
      "maldives"
    ],
    "Mali": [
      "mali"
    ],
    "Malta": [
      "malta"
    ],
    "Martinique": [
      "martinique"
    ],
    "Mauritania": [
      "mauritania"
    ],
    "Mauritius": [
      "mauritius"
    ],
    "Mayotte": [
      "mayotte"
    ],
    "Mexico": [
      "mexico"
    ],
    "Monaco": [
      "monaco"
    ],
    "Mongolia": [
      "mongolia"
    ],
    "Montenegro": [
      "montenegro"
    ],
    "Montserrat": [
      "montserrat"
    ],
    "Morocco": [
      "morocco"
    ],
    "Mozambique": [
      "mozambique"
    ],
    "Myanmar": [
      "myanmar"
    ],
    "Namibia": [
      "namibia"
    ],
    "Nauru": [
      "nauru"
    ],
    "Nepal": [
      "nepal"
    ],
    "New Caledonia": [
      "new caledonia"
    ],
    "New Zealand": [
      "new zealand"
    ],
    "Nicaragua": [
      "nicaragua"
    ],
    "Nigeria": [
      "nigeria"
    ],
    "Niue": [
      "niue"
    ],
    "Norway": [
      "norway"
    ],
    "Oman": [
      "oman"
    ],
    "Pakistan": [
      "pakistan"
    ],
    "Palau": [
      "palau"
    ],
    "Panama": [
      "panama"
    ],
    "Papua New Guinea": [
      "papua new guinea"
    ],
    "Paraguay": [
      "paraguay"
    ],
    "Peru": [
      "peru"
    ],
    "Poland": [
      "poland"
    ],
    "Portugal": [
      "portugal"
    ],
    "Puerto Rico": [
      "puerto rico"
    ],
    "Qatar": [
      "qatar"
    ],
    "Republic Of North Macedonia": [
      "republic of north macedonia"
    ],
    "Reunion": [
      "reunion"
    ],
    "Romania": [
      "romania"
    ],
    "Rwanda": [
      "rwanda"
    ],
    "Saint Kitts And Nevis": [
      "saint kitts and nevis"
    ],
    "Saint Lucia": [
      "saint lucia"
    ],
    "Saint Pierre And Miquelon": [
      "saint pierre and miquelon"
    ],
    "Saint Vincent And The Grenadines": [
      "saint vincent and the grenadines"
    ],
    "San Marino": [
      "san marino"
    ],
    "Sao Tome And Principe": [
      "sao tome and principe"
    ],
    "Saudi Arabia": [
      "saudi arabia"
    ],
    "Senegal": [
      "senegal"
    ],
    "Serbia": [
      "serbia"
    ],
    "Seychelles": [
      "seychelles"
    ],
    "Sierra Leone": [
      "sierra leone"
    ],
    "Singapore": [
      "singapore"
    ],
    "Slovakia": [
      "slovakia"
    ],
    "Slovenia": [
      "slovenia"
    ],
    "Solomon Islands": [
      "solomon islands"
    ],
    "Somalia": [
      "somalia"
    ],
    "South Africa": [
      "south africa"
    ],
    "South Korea": [
      "korea",
      "korean",
      "sk"
    ],
    "South Sudan": [
      "south sudan"
    ],
    "Spain": [
      "spain"
    ],
    "Sri Lanka": [
      "sri lanka"
    ],
    "State Of Palestine": [
      "state of palestine"
    ],
    "Suriname": [
      "suriname"
    ],
    "Svalbard And Jan Mayen": [
      "svalbard and jan mayen"
    ],
    "Sweden": [
      "sweden"
    ],
    "Switzerland": [
      "switzerland"
    ],
    "Syrian Arab Republic": [
      "syrian arab republic"
    ],
    "Taiwan, Republic Of China": [
      "taiwan, republic of china"
    ],
    "Tajikistan": [
      "tajikistan"
    ],
    "Thailand": [
      "thailand"
    ],
    "The Bahamas": [
      "the bahamas"
    ],
    "The Cayman Islands": [
      "the cayman islands"
    ],
    "The Central African Republic": [
      "the central african republic"
    ],
    "The Cocos Keeling Islands": [
      "the cocos keeling islands"
    ],
    "The Comoros": [
      "the comoros"
    ],
    "The Congo": [
      "the congo"
    ],
    "The Cook Islands": [
      "the cook islands"
    ],
    "The Democratic Peoples Republic Of Korea": [
      "the democratic peoples republic of korea"
    ],
    "The Democratic Republic Of The Congo": [
      "the democratic republic of the congo"
    ],
    "The Dominican Republic": [
      "the dominican republic"
    ],
    "The Falkland Islands Malvinas": [
      "the falkland islands malvinas"
    ],
    "The Faroe Islands": [
      "the faroe islands"
    ],
    "The French Southern Territories": [
      "the french southern territories"
    ],
    "The Gambia": [
      "the gambia"
    ],
    "The Holy See": [
      "the holy see"
    ],
    "The Lao Peoples Democratic Republic": [
      "the lao peoples democratic republic"
    ],
    "The Marshall Islands": [
      "the marshall islands"
    ],
    "The Netherlands": [
      "the netherlands"
    ],
    "The Niger": [
      "the niger"
    ],
    "The Philippines": [
      "the philippines"
    ],
    "The Republic Of Korea": [
      "the republic of korea"
    ],
    "The Republic Of Moldova": [
      "the republic of moldova"
    ],
    "The Russian Federation": [
      "the russian federation"
    ],
    "The Sudan": [
      "the sudan"
    ],
    "The Turks And Caicos Islands": [
      "the turks and caicos islands"
    ],
    "The United Arab Emirates": [
      "the united arab emirates"
    ],
    "The United Kingdom Of Great Britain And Northern Ireland": [
      "the united kingdom of great britain and northern ireland"
    ],
    "The United States Minor Outlying Islands": [
      "the united states minor outlying islands"
    ],
    "The United States Of America": [
      "the united states of america"
    ],
    "Timor Leste": [
      "timor leste"
    ],
    "Togo": [
      "togo"
    ],
    "Tonga": [
      "tonga"
    ],
    "Trinidad And Tobago": [
      "trinidad and tobago"
    ],
    "Tunisia": [
      "tunisia"
    ],
    "Turkmenistan": [
      "turkmenistan"
    ],
    "Tuvalu": [
      "tuvalu"
    ],
    "Türkiye": [
      "türkiye"
    ],
    "Uae": [
      "abu dhabi",
      "dubai",
      "united arab emirates"
    ],
    "Uganda": [
      "uganda"
    ],
    "Uk": [
      "britain",
      "england",
      "scotland",
      "united kingdom",
      "wales"
    ],
    "Ukraine": [
      "ukraine"
    ],
    "United Republic Of Tanzania": [
      "united republic of tanzania"
    ],
    "Uruguay": [
      "uruguay"
    ],
    "Us Virgin Islands": [
      "us virgin islands"
    ],
    "Usa": [
      "america",
      "american",
      "united states",
      "us"
    ],
    "Uzbekistan": [
      "uzbekistan"
    ],
    "Vanuatu": [
      "vanuatu"
    ],
    "Vietnam": [
      "vietnam"
    ],
    "Wallis And Futuna": [
      "wallis and futuna"
    ],
    "Yemen": [
      "yemen"
    ],
    "Zambia": [
      "zambia"
    ],
    "Zimbabwe": [
      "zimbabwe"
    ]
  },
  "languages": {
    "#english": [
      "#english"
    ],
    "#japan": [
      "#japan"
    ],
    "#spanish": [
      "#spanish"
    ],
    "+7 Languages": [
      "+7 languages"
    ],
    "1": [
      "1"
    ],
    "10 Additional Languages": [
      "10 additional languages"
    ],
    "111": [
      "111"
    ],
    "123": [
      "123"
    ],
    "128 Brazilian Portuguese": [
      "128 brazilian portuguese"
    ],
    "16 Other Languages": [
      "16 other languages"
    ],
    "17 Addtional Languages": [
      "17 addtional languages"
    ],
    "80s": [
      "80s"
    ],
    "Aboriginal Languages": [
      "aboriginal languages"
    ],
    "Afghan": [
      "afghan"
    ],
    "Africa": [
      "africa"
    ],
    "African": [
      "african"
    ],
    "Afrikaans": [
      "afrikaans"
    ],
    "Aka Bo": [
      "aka bo"
    ],
    "Akan": [
      "akan"
    ],
    "Albanian": [
      "albanian"
    ],
    "Amazigh": [
      "amazigh"
    ],
    "American English": [
      "american english"
    ],
    "Amharic": [
      "amharic"
    ],
    "Ancient Greek": [
      "ancient greek"
    ],
    "Andaluz.español": [
      "andaluz.español"
    ],
    "Anguilla": [
      "anguilla"
    ],
    "Annang": [
      "annang"
    ],
    "Anq": [
      "anq"
    ],
    "Anserma": [
      "anserma"
    ],
    "Apiaka": [
      "apiaka"
    ],
    "Ar": [
      "ar"
    ],
    "Arabesk": [
      "arabesk"
    ],
    "Arabi": [
      "arabi"
    ],
    "Arabic": [
      "arabic"
    ],
    "Arabic.": [
      "arabic."
    ],
    "Arapça": [
      "arapça"
    ],
    "Armenian": [
      "armenian"
    ],
    "Assamese": [
      "assamese"
    ],
    "Astur-leonese": [
      "astur-leonese"
    ],
    "Asturian": [
      "asturian"
    ],
    "Asunción": [
      "asunción"
    ],
    "Ateso": [
      "ateso"
    ],
    "Australian": [
      "australian"
    ],
    "Australian Indigenous": [
      "australian indigenous"
    ],
    "Aymara": [
      "aymara"
    ],
    "Azer": [
      "azer"
    ],
    "Azerbaijani": [
      "azerbaijani"
    ],
    "Azeri": [
      "azeri"
    ],
    "Azr": [
      "azr"
    ],
    "Bahasa Indonesia": [
      "bahasa indonesia"
    ],
    "Bahasa Jawa": [
      "bahasa jawa"
    ],
    "Bahasa Sunda": [
      "bahasa sunda"
    ],
    "Bambara": [
      "bambara"
    ],
    "Bangla": [
      "bangla"
    ],
    "Bashkir": [
      "bashkir"
    ],
    "Basque": [
      "basque"
    ],
    "Bavarian": [
      "bavarian"
    ],
    "Bearnese": [
      "bearnese"
    ],
    "Belarusian": [
      "belarusian"
    ],
    "Belge": [
      "belge"
    ],
    "Bengali": [
      "bengali"
    ],
    "Berbere": [
      "berbere"
    ],
    "Bering Aleut": [
      "bering aleut"
    ],
    "Bhojpuri": [
      "bhojpuri"
    ],
    "Bicolano": [
      "bicolano"
    ],
    "Bihari": [
      "bihari"
    ],
    "Bisaya": [
      "bisaya"
    ],
    "Bislama": [
      "bislama"
    ],
    "Bohemian": [
      "bohemian"
    ],
    "Bonaire": [
      "bonaire"
    ],
    "Bosn": [
      "bosn"
    ],
    "Bosnian": [
      "bosnian"
    ],
    "Brasil": [
      "brasil"
    ],
    "Brasileiro": [
      "brasileiro"
    ],
    "Brazilian Portuguese": [
      "brazilian portuguese"
    ],
    "Breton": [
      "breton"
    ],
    "Brezhoneg": [
      "brezhoneg"
    ],
    "British English": [
      "british english"
    ],
    "Bukharian": [
      "bukharian"
    ],
    "Bulgaria": [
      "bulgaria"
    ],
    "Bulgarian": [
      "bulgarian"
    ],
    "Burmese": [
      "burmese"
    ],
    "Cajun": [
      "cajun"
    ],
    "Canada": [
      "canada"
    ],
    "Canadian": [
      "canadian"
    ],
    "Canadian English": [
      "canadian english"
    ],
    "Cantonese": [
      "cantonese"
    ],
    "Capiznon": [
      "capiznon"
    ],
    "Caribbean English": [
      "caribbean english"
    ],
    "Carpatho-rusyn": [
      "carpatho-rusyn"
    ],
    "Cassubian": [
      "cassubian"
    ],
    "Castellano. Español": [
      "castellano. español"
    ],
    "Castilian": [
      "castilian"
    ],
    "Catalan": [
      "catalan"
    ],
    "Cebuano": [
      "cebuano"
    ],
    "Chaoshan Dialect": [
      "chaoshan dialect"
    ],
    "Chill": [
      "chill"
    ],
    "China": [
      "china"
    ],
    "Chinese": [
      "chinese"
    ],
    "Chipewyan": [
      "chipewyan"
    ],
    "Chuvash": [
      "chuvash"
    ],
    "Classical": [
      "classical"
    ],
    "Coatian": [
      "coatian"
    ],
    "Cochin": [
      "cochin"
    ],
    "Colombo": [
      "colombo"
    ],
    "Cooperativa": [
      "cooperativa"
    ],
    "Cornish": [
      "cornish"
    ],
    "Coronel Oviedo": [
      "coronel oviedo"
    ],
    "Corsu": [
      "corsu"
    ],
    "Cree": [
      "cree"
    ],
    "Creole": [
      "creole"
    ],
    "Croatia": [
      "croatia"
    ],
    "Croatian": [
      "croatian"
    ],
    "Czech": [
      "czech"
    ],
    "Dai Language": [
      "dai language"
    ],
    "Dan": [
      "dan"
    ],
    "Danish": [
      "danish"
    ],
    "Dansk/oldnordisk": [
      "dansk/oldnordisk"
    ],
    "Deu": [
      "deu"
    ],
    "Deutsch Fränkisch": [
      "deutsch fränkisch"
    ],
    "Dhivehi": [
      "dhivehi"
    ],
    "Dialects": [
      "dialects"
    ],
    "Discography": [
      "discography"
    ],
    "Durch": [
      "durch"
    ],
    "Dutch": [
      "dutch"
    ],
    "Dutch Colombo": [
      "dutch colombo"
    ],
    "E": [
      "e"
    ],
    "Eesti": [
      "eesti"
    ],
    "Efik": [
      "efik"
    ],
    "Egnlish": [
      "egnlish"
    ],
    "Eight Additional Languages": [
      "eight additional languages"
    ],
    "Eletrica": [
      "eletrica"
    ],
    "En Gb": [
      "en gb"
    ],
    "Encarnación": [
      "encarnación"
    ],
    "Engels": [
      "engels"
    ],
    "Engilsh": [
      "engilsh"
    ],
    "Engilsh Uk": [
      "engilsh uk"
    ],
    "Engish": [
      "engish"
    ],
    "Englisg": [
      "englisg"
    ],
    "English": [
      "english"
    ],
    "English Hindi": [
      "english hindi"
    ],
    "English Russian": [
      "english russian"
    ],
    "English Spanish": [
      "english spanish"
    ],
    "English Uk": [
      "english uk"
    ],
    "English/": [
      "english/"
    ],
    "English/ España/ Russian /francia /italia": [
      "english/ españa/ russian /francia /italia"
    ],
    "English/ Russian /francia /españa": [
      "english/ russian /francia /españa"
    ],
    "English/russian": [
      "english/russian"
    ],
    "English/sotho/afrikaans": [
      "english/sotho/afrikaans"
    ],
    "English/tagalog": [
      "english/tagalog"
    ],
    "Englisj": [
      "englisj"
    ],
    "Engllish": [
      "engllish"
    ],
    "Englsh": [
      "englsh"
    ],
    "Englsih": [
      "englsih"
    ],
    "Esapa": [
      "esapa"
    ],
    "Espa": [
      "espa"
    ],
    "Espana": [
      "espana"
    ],
    "Espanish": [
      "espanish"
    ],
    "España": [
      "españa"
    ],
    "Españo": [
      "españo"
    ],
    "Español - Latinoamerica": [
      "español - latinoamerica"
    ],
    "Español Argentina": [
      "español argentina"
    ],
    "Español Asunción": [
      "español asunción"
    ],
    "Español Chile": [
      "español chile"
    ],
    "Español Colombia": [
      "español colombia"
    ],
    "Español Ecuador": [
      "español ecuador"
    ],
    "Español In Catalán": [
      "español in catalán"
    ],
    "Español Ingles": [
      "español ingles"
    ],
    "Español Internacional": [
      "español internacional"
    ],
    "Español Mexico": [
      "español mexico"
    ],
    "Español Paraguay": [
      "español paraguay"
    ],
    "Español Peruano": [
      "español peruano"
    ],
    "Espaňol": [
      "espaňol"
    ],
    "Esperanto": [
      "esperanto"
    ],
    "Espsñol": [
      "espsñol"
    ],
    "Estonia": [
      "estonia"
    ],
    "Estonian": [
      "estonian"
    ],
    "Euskera": [
      "euskera"
    ],
    "Evergreens": [
      "evergreens"
    ],
    "F": [
      "f"
    ],
    "Faroese": [
      "faroese"
    ],
    "Fge Spain": [
      "fge spain"
    ],
    "Fijian": [
      "fijian"
    ],
    "Fijian Hindi": [
      "fijian hindi"
    ],
    "Filipino": [
      "filipino"
    ],
    "Finish": [
      "finish"
    ],
    "Finland": [
      "finland"
    ],
    "Finnish": [
      "finnish"
    ],
    "Flammish": [
      "flammish"
    ],
    "Flemish": [
      "flemish"
    ],
    "Fra": [
      "fra"
    ],
    "Francaise": [
      "francaise"
    ],
    "Franch": [
      "franch"
    ],
    "Francés": [
      "francés"
    ],
    "French": [
      "francais",
      "french"
    ],
    "Frenchhttps://rfiswahili96k.ice.infomaniak.ch/rfis": [
      "frenchhttps://rfiswahili96k.ice.infomaniak.ch/rfis"
    ],
    "Fries": [
      "fries"
    ],
    "Frysk": [
      "frysk"
    ],
    "Fränkisch": [
      "fränkisch"
    ],
    "Fulani": [
      "fulani"
    ],
    "Furlan": [
      "furlan"
    ],
    "Gaeilge": [
      "gaeilge"
    ],
    "Gaelic": [
      "gaelic"
    ],
    "Gagana Samoa": [
      "gagana samoa"
    ],
    "Gagauz": [
      "gagauz"
    ],
    "Galaic–portuguese": [
      "galaic–portuguese"
    ],
    "Galego": [
      "galego"
    ],
    "Galician": [
      "galician"
    ],
    "Gallego": [
      "gallego"
    ],
    "Gallo": [
      "gallo"
    ],
    "Garifuna": [
      "garifuna"
    ],
    "Gascon": [
      "gascon"
    ],
    "Geopn": [
      "geopn"
    ],
    "Georgian": [
      "georgian"
    ],
    "Ger": [
      "ger"
    ],
    "German": [
      "german"
    ],
    "Germanhttps://stream.laut.fm/deutrockosterreich": [
      "germanhttps://stream.laut.fm/deutrockosterreich"
    ],
    "Gernan": [
      "gernan"
    ],
    "Ghana": [
      "ghana"
    ],
    "Global": [
      "global"
    ],
    "Greek": [
      "greek"
    ],
    "Greel": [
      "greel"
    ],
    "Guarani": [
      "guarani"
    ],
    "Gujarati": [
      "gujarati"
    ],
    "Gujrati": [
      "gujrati"
    ],
    "Gwich'in": [
      "gwich'in"
    ],
    "Haiti Creole": [
      "haiti creole"
    ],
    "Haitian Creole": [
      "haitian creole"
    ],
    "Hakka": [
      "hakka"
    ],
    "Haryanvi": [
      "haryanvi"
    ],
    "Hausa": [
      "hausa"
    ],
    "Hausa L": [
      "hausa l"
    ],
    "Hawaiian": [
      "hawaiian"
    ],
    "Hebrew": [
      "hebrew"
    ],
    "Hh": [
      "hh"
    ],
    "Hindi": [
      "bollywood",
      "hindi",
      "hindustani"
    ],
    "Hindi English Assamese": [
      "hindi english assamese"
    ],
    "Hindu": [
      "hindu"
    ],
    "Hiphop": [
      "hiphop"
    ],
    "Hits": [
      "hits"
    ],
    "Hokkien": [
      "hokkien"
    ],
    "Holland": [
      "holland"
    ],
    "Http://stream-uk1.radioparadise.com:80/aac-32": [
      "http://stream-uk1.radioparadise.com:80/aac-32"
    ],
    "Http://wdr-1live-live.icecast.wdr.de": [
      "http://wdr-1live-live.icecast.wdr.de"
    ],
    "Hun": [
      "hun"
    ],
    "Hungarian": [
      "hungarian"
    ],
    "Ibibio": [
      "ibibio"
    ],
    "Ibo": [
      "ibo"
    ],
    "Icelandic": [
      "icelandic"
    ],
    "Illonggo": [
      "illonggo"
    ],
    "Ilocano": [
      "ilocano"
    ],
    "Ilokano": [
      "ilokano"
    ],
    "Ilonggo": [
      "ilonggo"
    ],
    "Inari Sámi": [
      "inari sámi"
    ],
    "Indian": [
      "indian"
    ],
    "Indigenous Languages": [
      "indigenous languages"
    ],
    "Indonesian": [
      "indonesian"
    ],
    "Ingles Español": [
      "ingles español"
    ],
    "Inglés/portugués/español": [
      "inglés/portugués/español"
    ],
    "Inuktituk": [
      "inuktituk"
    ],
    "Inuvialuktun": [
      "inuvialuktun"
    ],
    "Iran": [
      "iran"
    ],
    "Irani": [
      "irani"
    ],
    "Iranian": [
      "iranian"
    ],
    "Iraqi Turkmen": [
      "iraqi turkmen"
    ],
    "Irish": [
      "irish"
    ],
    "Isindebele": [
      "isindebele"
    ],
    "Isixhosa": [
      "isixhosa"
    ],
    "Isizulu": [
      "isizulu"
    ],
    "Italian": [
      "italian"
    ],
    "Jamaicaans-patois": [
      "jamaicaans-patois"
    ],
    "Jamaican": [
      "jamaican"
    ],
    "Japanese": [
      "japanese"
    ],
    "Japones": [
      "japones"
    ],
    "Java": [
      "java"
    ],
    "Javanese": [
      "javanese"
    ],
    "Jawa": [
      "jawa"
    ],
    "Juma": [
      "juma"
    ],
    "Kachin": [
      "kachin"
    ],
    "Kalaallisut": [
      "kalaallisut"
    ],
    "Kalaallusit": [
      "kalaallusit"
    ],
    "Kannada": [
      "kannada"
    ],
    "Kapampangan": [
      "kapampangan"
    ],
    "Kashmiri": [
      "kashmiri"
    ],
    "Kashubian": [
      "kashubian"
    ],
    "Kazakh": [
      "kazakh"
    ],
    "Kelantanese Malay": [
      "kelantanese malay"
    ],
    "Keski-suomi": [
      "keski-suomi"
    ],
    "Khmer": [
      "khmer"
    ],
    "Kikongo": [
      "kikongo"
    ],
    "Kikuyu Swahili": [
      "kikuyu swahili"
    ],
    "Kinand": [
      "kinand"
    ],
    "Kinyarwanda & Kiswahili": [
      "kinyarwanda & kiswahili"
    ],
    "Kirmanci": [
      "kirmanci"
    ],
    "Kiswahili": [
      "kiswahili"
    ],
    "Kiwi": [
      "kiwi"
    ],
    "Konkani": [
      "konkani"
    ],
    "Korean": [
      "korean"
    ],
    "Kroatisch": [
      "kroatisch"
    ],
    "Kupsabiny": [
      "kupsabiny"
    ],
    "Kurdi": [
      "kurdi"
    ],
    "Kurdish": [
      "kurdish"
    ],
    "Kurdish.": [
      "kurdish."
    ],
    "Kyrgyz": [
      "kyrgyz"
    ],
    "Kölscher Dialekt": [
      "kölscher dialekt"
    ],
    "Ladin": [
      "ladin"
    ],
    "Ladino": [
      "ladino"
    ],
    "Latin": [
      "latin"
    ],
    "Latino": [
      "latino"
    ],
    "Latinoamerica": [
      "latinoamerica"
    ],
    "Latvia": [
      "latvia"
    ],
    "Latvian": [
      "latvian"
    ],
    "Latviešu": [
      "latviešu"
    ],
    "Lebanese": [
      "lebanese"
    ],
    "Limburgs": [
      "limburgs"
    ],
    "Lingala": [
      "lingala"
    ],
    "Lisu": [
      "lisu"
    ],
    "Lithuanian": [
      "lithuanian"
    ],
    "Louisiana French": [
      "louisiana french"
    ],
    "Low German": [
      "low german"
    ],
    "Lower Arrernte": [
      "lower arrernte"
    ],
    "Lower Sorbian": [
      "lower sorbian"
    ],
    "Lubwisi": [
      "lubwisi"
    ],
    "Luganda": [
      "luganda"
    ],
    "Luganda English": [
      "luganda english"
    ],
    "Lugisu": [
      "lugisu"
    ],
    "Lugwere": [
      "lugwere"
    ],
    "Lukhonzo": [
      "lukhonzo"
    ],
    "Lumasaba Luganda English": [
      "lumasaba luganda english"
    ],
    "Luo": [
      "luo"
    ],
    "Lusoga": [
      "lusoga"
    ],
    "Luxembourgish": [
      "luxembourgish"
    ],
    "Macedonian": [
      "macedonian"
    ],
    "Magesh": [
      "magesh"
    ],
    "Malagasy": [
      "malagasy"
    ],
    "Malay": [
      "malay"
    ],
    "Malayalam": [
      "malayalam",
      "malayalee"
    ],
    "Malgache": [
      "malgache"
    ],
    "Maltese": [
      "maltese"
    ],
    "Malti": [
      "malti"
    ],
    "Mandarin": [
      "mandarin"
    ],
    "Manx": [
      "manx"
    ],
    "Marathi": [
      "marathi"
    ],
    "Masurian": [
      "masurian"
    ],
    "Messapic": [
      "messapic"
    ],
    "Mexicano": [
      "mexicano"
    ],
    "Minang": [
      "minang"
    ],
    "Mixteco": [
      "mixteco"
    ],
    "Ml": [
      "ml"
    ],
    "Moldovian": [
      "moldovian"
    ],
    "Mongolian": [
      "mongolian"
    ],
    "Monoglian": [
      "monoglian"
    ],
    "Montenegrin": [
      "montenegrin"
    ],
    "Montenegro": [
      "montenegro"
    ],
    "Moroccan Arabic": [
      "moroccan arabic"
    ],
    "Moselle Romance": [
      "moselle romance"
    ],
    "Multiculti": [
      "multiculti"
    ],
    "Muromian": [
      "muromian"
    ],
    "N/a": [
      "n/a"
    ],
    "Nahuatl": [
      "nahuatl"
    ],
    "Navajo": [
      "navajo"
    ],
    "Nederland": [
      "nederland"
    ],
    "Nedersaksisch": [
      "nedersaksisch"
    ],
    "Nepali": [
      "nepali"
    ],
    "Nethe": [
      "nethe"
    ],
    "New Orleans Louisiana": [
      "new orleans louisiana"
    ],
    "Ngakarimojong": [
      "ngakarimojong"
    ],
    "Noongar": [
      "noongar"
    ],
    "Noongar Aboriginal": [
      "noongar aboriginal"
    ],
    "Norddeutsch": [
      "norddeutsch"
    ],
    "Noric": [
      "noric"
    ],
    "Norn": [
      "norn"
    ],
    "Norsk": [
      "norsk"
    ],
    "North Slavey": [
      "north slavey"
    ],
    "Northern Manx": [
      "northern manx"
    ],
    "Northern Sámi": [
      "northern sámi"
    ],
    "Norwegian": [
      "norwegian"
    ],
    "Norwwegian": [
      "norwwegian"
    ],
    "Novokuznetzk": [
      "novokuznetzk"
    ],
    "Nuxalk": [
      "nuxalk"
    ],
    "Nyoongar": [
      "nyoongar"
    ],
    "Nyungar": [
      "nyungar"
    ],
    "Occitan": [
      "occitan"
    ],
    "Odia": [
      "odia"
    ],
    "Oilsjters": [
      "oilsjters"
    ],
    "Old Novgorod": [
      "old novgorod"
    ],
    "Online Radio": [
      "online radio"
    ],
    "Only Music": [
      "only music"
    ],
    "Originarios": [
      "originarios"
    ],
    "Oromo": [
      "oromo"
    ],
    "Oromo Amharic Somali": [
      "oromo amharic somali"
    ],
    "Oscan": [
      "oscan"
    ],
    "Ossetian": [
      "ossetian"
    ],
    "Others": [
      "others"
    ],
    "Pacific": [
      "pacific"
    ],
    "Pacifica Multi Ethnic": [
      "pacifica multi ethnic"
    ],
    "Palestinian": [
      "palestinian"
    ],
    "Pali": [
      "pali"
    ],
    "Panjabi": [
      "panjabi"
    ],
    "Papiamentu": [
      "papiamentu"
    ],
    "Paraguay": [
      "paraguay"
    ],
    "Pashto": [
      "pashto"
    ],
    "Pashto /urdu": [
      "pashto /urdu"
    ],
    "Pazeh": [
      "pazeh"
    ],
    "Pedro Juan Caballero": [
      "pedro juan caballero"
    ],
    "Persian": [
      "persian"
    ],
    "Pfälzisch": [
      "pfälzisch"
    ],
    "Philipsburg": [
      "philipsburg"
    ],
    "Pigin": [
      "pigin"
    ],
    "Polish": [
      "polish"
    ],
    "Polynesia": [
      "polynesia"
    ],
    "Pop Music": [
      "pop music"
    ],
    "Por": [
      "por"
    ],
    "Porguês": [
      "porguês"
    ],
    "Port": [
      "port"
    ],
    "Portguese": [
      "portguese"
    ],
    "Portoguese": [
      "portoguese"
    ],
    "Portu": [
      "portu"
    ],
    "Portugues Do Braasil": [
      "portugues do braasil"
    ],
    "Portugues Do Brasil": [
      "portugues do brasil"
    ],
    "Portugues Francês": [
      "portugues francês"
    ],
    "Portuguese": [
      "portugues",
      "portuguese"
    ],
    "Portugués": [
      "portugués"
    ],
    "Português (br)": [
      "português (br)"
    ],
    "Português (brasil)": [
      "português (brasil)"
    ],
    "Português Brasil": [
      "português  brasil"
    ],
    "Pt-br": [
      "pt-br"
    ],
    "Punjab": [
      "punjab"
    ],
    "Punjabi": [
      "punjab",
      "punjabi"
    ],
    "Qirimtatar": [
      "qirimtatar"
    ],
    "Quechua": [
      "quechua"
    ],
    "Quiché": [
      "quiché"
    ],
    "Québecois": [
      "québecois"
    ],
    "R": [
      "r"
    ],
    "Rnb": [
      "rnb"
    ],
    "Rock": [
      "rock"
    ],
    "Roma": [
      "roma"
    ],
    "Romani": [
      "romani"
    ],
    "Romania": [
      "romania"
    ],
    "Romanian": [
      "romanian"
    ],
    "Romansh": [
      "romansh"
    ],
    "Romany": [
      "romany"
    ],
    "Româna": [
      "româna"
    ],
    "Românä": [
      "românä"
    ],
    "Română": [
      "română"
    ],
    "Roots": [
      "roots"
    ],
    "Rossia": [
      "rossia"
    ],
    "Runyakitara": [
      "runyakitara"
    ],
    "Runyankole": [
      "runyankole"
    ],
    "Rus": [
      "rus"
    ],
    "Russian": [
      "russian"
    ],
    "Russian/yakut": [
      "russian/yakut"
    ],
    "S": [
      "s"
    ],
    "Saba": [
      "saba"
    ],
    "Saint Lucian Creole": [
      "saint lucian creole"
    ],
    "Samba E Pagode": [
      "samba e pagode"
    ],
    "Sami": [
      "sami"
    ],
    "Samoan": [
      "samoan"
    ],
    "San Miguel": [
      "san miguel"
    ],
    "San Salvador": [
      "san salvador"
    ],
    "Sanskrit": [
      "sanskrit"
    ],
    "Sardinian": [
      "sardinian"
    ],
    "Satanic": [
      "satanic"
    ],
    "Schweizerdeutsch": [
      "schweizerdeutsch"
    ],
    "Sepedi": [
      "sepedi"
    ],
    "Serbian": [
      "serbian"
    ],
    "Sesotho": [
      "sesotho"
    ],
    "Setswana": [
      "setswana"
    ],
    "Shimaoré": [
      "shimaoré"
    ],
    "Shona": [
      "shona"
    ],
    "Shqip": [
      "shqip"
    ],
    "Shqip Macedonia": [
      "shqip macedonia"
    ],
    "Silesian": [
      "silesian"
    ],
    "Sindhi": [
      "sindhi"
    ],
    "Sing Along": [
      "sing along"
    ],
    "Sinhala": [
      "sinhala"
    ],
    "Sinhalese": [
      "sinhalese"
    ],
    "Sint Maarten": [
      "sint maarten"
    ],
    "Siswati": [
      "siswati"
    ],
    "Skolt Sámi": [
      "skolt sámi"
    ],
    "Slovak": [
      "slovak"
    ],
    "Slovenian": [
      "slovenian"
    ],
    "Slovenski": [
      "slovenski"
    ],
    "Slowenisch": [
      "slowenisch"
    ],
    "Soft": [
      "soft"
    ],
    "Somali": [
      "somali"
    ],
    "Sorbian": [
      "sorbian"
    ],
    "Soul": [
      "soul"
    ],
    "South Asian Languages": [
      "south asian languages"
    ],
    "South Slavey": [
      "south slavey"
    ],
    "Spain": [
      "spain"
    ],
    "Span": [
      "span"
    ],
    "Spani": [
      "spani"
    ],
    "Spanish": [
      "espanol",
      "spanish"
    ],
    "Spanish Saba": [
      "spanish saba"
    ],
    "Sranan Tongo": [
      "sranan tongo"
    ],
    "Standard Moroccan Amazigh": [
      "standard moroccan amazigh"
    ],
    "Suomi": [
      "suomi"
    ],
    "Swabian": [
      "swabian"
    ],
    "Swahili": [
      "swahili"
    ],
    "Swahili/": [
      "swahili/"
    ],
    "Swe": [
      "swe"
    ],
    "Swedish": [
      "swedish"
    ],
    "Swiss": [
      "swiss"
    ],
    "Swiss German": [
      "swiss german"
    ],
    "Sámi": [
      "sámi"
    ],
    "Sächsisch": [
      "sächsisch"
    ],
    "Tachelhite": [
      "tachelhite"
    ],
    "Tagalog": [
      "tagalog"
    ],
    "Tahitian": [
      "tahitian"
    ],
    "Tajik": [
      "tajik"
    ],
    "Tamaulipas": [
      "tamaulipas"
    ],
    "Tamazight": [
      "tamazight"
    ],
    "Tamil": [
      "tamil",
      "tamizh"
    ],
    "Tatar": [
      "tatar"
    ],
    "Te Reo": [
      "te reo"
    ],
    "Te Reo Maori": [
      "te reo maori"
    ],
    "Telugu": [
      "telegu",
      "telugu"
    ],
    "Teochew": [
      "teochew"
    ],
    "Thai": [
      "thai"
    ],
    "Tibetan": [
      "tibetan"
    ],
    "Tigre": [
      "tigre"
    ],
    "Tigrigna": [
      "tigrigna"
    ],
    "Tlapaneco": [
      "tlapaneco"
    ],
    "Tlicho": [
      "tlicho"
    ],
    "Top 40": [
      "top 40"
    ],
    "Torres Strait Creole": [
      "torres strait creole"
    ],
    "Tr": [
      "tr"
    ],
    "Tshiluba": [
      "tshiluba"
    ],
    "Tshivenda": [
      "tshivenda"
    ],
    "Tshivenḓa": [
      "tshivenḓa"
    ],
    "Tule Kaweah Yokuts": [
      "tule kaweah yokuts"
    ],
    "Tunisian": [
      "tunisian"
    ],
    "Turkish": [
      "turkish"
    ],
    "Turkmen": [
      "turkmen"
    ],
    "Turkt": [
      "turkt"
    ],
    "Turkçe": [
      "turkçe"
    ],
    "Twi": [
      "twi"
    ],
    "Türkisch": [
      "türkisch"
    ],
    "Türkish": [
      "türkish"
    ],
    "Ua": [
      "ua"
    ],
    "Ucrânia": [
      "ucrânia"
    ],
    "Ukrainian": [
      "ukrainian"
    ],
    "Ukrainisch": [
      "ukrainisch"
    ],
    "Ukranian": [
      "ukranian"
    ],
    "Ungarisch": [
      "ungarisch"
    ],
    "Upper Chinook": [
      "upper chinook"
    ],
    "Upper Sorbian": [
      "upper sorbian"
    ],
    "Urdu": [
      "urdu"
    ],
    "Urdu/punjabi/seraiki": [
      "urdu/punjabi/seraiki"
    ],
    "Urhobo": [
      "urhobo"
    ],
    "Us": [
      "us"
    ],
    "Usa": [
      "usa"
    ],
    "Uyghur": [
      "uyghur"
    ],
    "Uzbek": [
      "uzbek"
    ],
    "Uzbek،russian": [
      "uzbek،russian"
    ],
    "Vaporwave": [
      "vaporwave"
    ],
    "Various Filipino Languages": [
      "various filipino languages"
    ],
    "Various Languages": [
      "various languages"
    ],
    "Vietnamese": [
      "vietnamese"
    ],
    "Welsh": [
      "welsh"
    ],
    "Willemstad": [
      "willemstad"
    ],
    "Xhosa": [
      "xhosa"
    ],
    "Xitsonga": [
      "xitsonga"
    ],
    "Yiddish": [
      "yiddish"
    ],
    "Yoruba": [
      "yoruba"
    ],
    "Yucatec Maya": [
      "yucatec maya"
    ],
    "Yugoslavian": [
      "yugoslavian"
    ],
    "Yupik": [
      "yupik"
    ],
    "Zaiwa": [
      "zaiwa"
    ],
    "Zeelandic": [
      "zeelandic"
    ],
    "Zulu": [
      "zulu"
    ],
    "Česky": [
      "česky"
    ],
    "Śląski": [
      "śląski"
    ],
    "Английский": [
      "английский"
    ],
    "Беларуская": [
      "беларуская"
    ],
    "Испанский": [
      "испанский"
    ],
    "Молдавский": [
      "молдавский"
    ],
    "Неизвестен": [
      "неизвестен"
    ],
    "Осетинский": [
      "осетинский"
    ],
    "Ру": [
      "ру"
    ],
    "Српски": [
      "српски"
    ],
    "Татарский": [
      "татарский"
    ],
    "Укр": [
      "укр"
    ],
    "Украина": [
      "украина"
    ],
    "Церковнославянский": [
      "церковнославянский"
    ],
    "Чукотский": [
      "чукотский"
    ],
    "Язык: Russia": [
      "язык: russia"
    ],
    "Язык: Ру": [
      "язык: ру"
    ],
    "Язык: Русский": [
      "язык: русский"
    ],
    "Язык: Русский Английский": [
      "язык: русский английский"
    ],
    "العربية": [
      "العربية"
    ],
    "عربي": [
      "عربي"
    ],
    "ภาษาไทย": [
      "ภาษาไทย"
    ],
    "中国": [
      "中国"
    ],
    "国语": [
      "国语"
    ],
    "師傅傅": [
      "師傅傅"
    ],
    "德语": [
      "德语"
    ],
    "月南": [
      "月南"
    ],
    "音乐": [
      "音乐"
    ]
  },
  "tags": {
    "pop": [
      "pop"
    ],
    "radio": [
      "radio"
    ],
    "estación": [
      "estación"
    ],
    "music": [
      "music"
    ],
    "méxico": [
      "méxico"
    ],
    "fm": [
      "fm"
    ],
    "entretenimiento": [
      "entretenimiento"
    ],
    "música": [
      "música"
    ],
    "moi merino": [
      "moi merino"
    ],
    "norteamérica": [
      "norteamérica"
    ],
    "latinoamérica": [
      "latinoamérica"
    ],
    "rock": [
      "rock"
    ],
    "español": [
      "español"
    ],
    "news": [
      "news"
    ],
    "pop music": [
      "pop music"
    ],
    "américa": [
      "américa"
    ],
    "música en español": [
      "música en español"
    ],
    "música pop": [
      "música pop"
    ],
    "dance": [
      "dance"
    ],
    "oldies": [
      "oldies"
    ],
    "pop rock": [
      "pop rock"
    ],
    "jazz": [
      "jazz"
    ],
    "80s": [
      "80s"
    ],
    "hits": [
      "hits"
    ],
    "talk": [
      "talk"
    ],
    "regional": [
      "regional"
    ],
    "música regional": [
      "música regional"
    ],
    "local news": [
      "local news"
    ],
    "mexico": [
      "mexico"
    ],
    "regional mexicana": [
      "regional mexicana"
    ],
    "música popular mexicana": [
      "música popular mexicana"
    ],
    "regional mexican": [
      "regional mexican"
    ],
    "top 40": [
      "top 40"
    ],
    "mex": [
      "mex"
    ],
    "mx": [
      "mx"
    ],
    "90s": [
      "90s"
    ],
    "mexican music": [
      "mexican music"
    ],
    "classic rock": [
      "classic rock"
    ],
    "música del recuerdo": [
      "música del recuerdo"
    ],
    "electronic": [
      "electronic"
    ],
    "traditional mexican music": [
      "traditional mexican music"
    ],
    "house": [
      "house"
    ],
    "juvenil": [
      "juvenil"
    ],
    "public radio": [
      "public radio"
    ],
    "classic hits": [
      "classic hits"
    ],
    "regional music": [
      "regional music"
    ],
    "local radio": [
      "local radio"
    ],
    "alternative": [
      "alternative"
    ],
    "regional radio": [
      "regional radio"
    ],
    "musica": [
      "musica"
    ],
    "grupera": [
      "grupera"
    ],
    "adult contemporary": [
      "adult contemporary"
    ],
    "am": [
      "am"
    ],
    "classical": [
      "classical"
    ],
    "ciudad de méxico": [
      "ciudad de méxico"
    ],
    "noticias": [
      "noticias"
    ],
    "community radio": [
      "community radio"
    ],
    "música y noticias": [
      "música y noticias"
    ],
    "valle de méxico": [
      "valle de méxico"
    ],
    "pop en español e inglés": [
      "pop en español e inglés"
    ],
    "música variada": [
      "música variada"
    ],
    "música en español e inglés": [
      "música en español e inglés"
    ],
    "música regional mexicana": [
      "música regional mexicana"
    ],
    "música mexicana": [
      "música mexicana"
    ],
    "latin pop": [
      "latin pop"
    ],
    "grupero": [
      "grupero"
    ],
    "top hits": [
      "top hits"
    ],
    "mexico city": [
      "mexico city"
    ],
    "70s": [
      "70s"
    ],
    "retro": [
      "retro"
    ],
    "country": [
      "country"
    ],
    "banda": [
      "banda"
    ],
    "top40": [
      "top40"
    ],
    "chillout": [
      "chillout"
    ],
    "christian": [
      "christian"
    ],
    "news talk": [
      "news talk"
    ],
    "cdmx": [
      "cdmx"
    ],
    "mvs radio": [
      "mvs radio"
    ],
    "mvs": [
      "mvs"
    ],
    "clásicos": [
      "clásicos"
    ],
    "noticias locales": [
      "noticias locales"
    ],
    "ambient": [
      "ambient"
    ],
    "musica regional mexicana": [
      "musica regional mexicana"
    ],
    "música tradicional mexicana": [
      "música tradicional mexicana"
    ],
    "techno": [
      "techno"
    ],
    "eclectic": [
      "eclectic"
    ],
    "noticias en español": [
      "noticias en español"
    ],
    "musica regional": [
      "musica regional"
    ],
    "80's": [
      "80's"
    ],
    "noticias y comentarios": [
      "noticias y comentarios"
    ],
    "lounge": [
      "lounge"
    ],
    "top charts": [
      "top charts"
    ],
    "musica mexicana": [
      "musica mexicana"
    ],
    "musica tradicional mexicana": [
      "musica tradicional mexicana"
    ],
    "musica latina": [
      "musica latina"
    ],
    "easy listening": [
      "easy listening"
    ],
    "culture": [
      "culture"
    ],
    "indie": [
      "indie"
    ],
    "música en inglés": [
      "música en inglés"
    ],
    "baladas en español": [
      "baladas en español"
    ],
    "pop en inglés": [
      "pop en inglés"
    ],
    "radio hablada": [
      "radio hablada"
    ],
    "balada pop": [
      "balada pop"
    ],
    "pop dance": [
      "pop dance"
    ],
    "alternative rock": [
      "alternative rock"
    ],
    "electro": [
      "electro"
    ],
    "musica latinoamericana": [
      "musica latinoamericana"
    ],
    "sureste": [
      "sureste"
    ],
    "hot adult contemporary": [
      "hot adult contemporary"
    ],
    "90's": [
      "90's"
    ],
    "hiphop": [
      "hiphop"
    ],
    "hablada": [
      "hablada"
    ],
    "80er": [
      "80er"
    ],
    "california": [
      "california"
    ],
    "top 100": [
      "top 100"
    ],
    "rap": [
      "rap"
    ],
    "sports": [
      "sports"
    ],
    "funk": [
      "funk"
    ],
    "variety": [
      "variety"
    ],
    "information": [
      "information"
    ],
    "baladas": [
      "baladas"
    ],
    "edm": [
      "edm"
    ],
    "online": [
      "online"
    ],
    "soul": [
      "soul"
    ],
    "folk": [
      "folk"
    ],
    "various": [
      "various"
    ],
    "balada en español": [
      "balada en español"
    ],
    "radiorama": [
      "radiorama"
    ],
    "hip-hop": [
      "hip",
      "hip-hop",
      "hop"
    ],
    "classics": [
      "classics"
    ],
    "schlager": [
      "schlager"
    ],
    "smooth jazz": [
      "smooth jazz"
    ],
    "radio online": [
      "radio online"
    ],
    "world music": [
      "world music"
    ],
    "noticias nacionales e internacionales": [
      "noticias nacionales e internacionales"
    ],
    "college radio": [
      "college radio"
    ],
    "latin music": [
      "latin music"
    ],
    "top 40 hits": [
      "top 40 hits"
    ],
    "reggae": [
      "reggae"
    ],
    "online only": [
      "online only"
    ],
    "2000s": [
      "2000s"
    ],
    "disco": [
      "disco"
    ],
    "contemporary hits radio": [
      "contemporary hits radio"
    ],
    "pop en español": [
      "pop en español"
    ],
    "local music": [
      "local music"
    ],
    "radiópolis": [
      "radiópolis"
    ],
    "balada": [
      "balada"
    ],
    "metal": [
      "metal"
    ],
    "top": [
      "top"
    ],
    "non-commercial": [
      "commercial",
      "non",
      "non-commercial"
    ],
    "exa": [
      "exa"
    ],
    "exa fm": [
      "exa fm"
    ],
    "ponte exa": [
      "ponte exa"
    ],
    "deep house": [
      "deep house"
    ],
    "iheart radio": [
      "iheart radio"
    ],
    "clásicos en inglés": [
      "clásicos en inglés"
    ],
    "la estación exacta": [
      "la estación exacta"
    ],
    "la estación naranja": [
      "la estación naranja"
    ],
    "veracruz": [
      "veracruz"
    ],
    "public service": [
      "public service"
    ],
    "60s": [
      "60s"
    ],
    "blues": [
      "blues"
    ],
    "grupo acir": [
      "grupo acir"
    ],
    "iheart": [
      "iheart"
    ],
    "jalisco": [
      "jalisco"
    ],
    "acir": [
      "acir"
    ],
    "contemporary hits": [
      "contemporary hits"
    ],
    "romantic": [
      "romantic"
    ],
    "pop clásico": [
      "pop clásico"
    ],
    "local": [
      "local"
    ],
    "chihuahua": [
      "chihuahua"
    ],
    "trance": [
      "trance"
    ],
    "adult hits": [
      "adult hits"
    ],
    "tropical": [
      "tropical"
    ],
    "internet": [
      "internet"
    ],
    "hard rock": [
      "hard rock"
    ],
    "free": [
      "free"
    ],
    "talk radio": [
      "talk radio"
    ],
    "banda norteña": [
      "banda norteña"
    ],
    "multimedios radio": [
      "multimedios radio"
    ],
    "multimedios": [
      "multimedios"
    ],
    "classical music": [
      "classical music"
    ],
    "nuevo león": [
      "nuevo león"
    ],
    "combo": [
      "combo"
    ],
    "90er": [
      "90er"
    ],
    "musica romantica": [
      "musica romantica"
    ],
    "románticas": [
      "románticas"
    ],
    "radio pública": [
      "radio pública"
    ],
    "pública": [
      "pública"
    ],
    "noticias cortas": [
      "noticias cortas"
    ],
    "university radio": [
      "university radio"
    ],
    "romántica": [
      "romántica"
    ],
    "urban": [
      "urban"
    ],
    "monterrey": [
      "monterrey"
    ],
    "cultural": [
      "cultural"
    ],
    "grupo audiorama comunicaciones": [
      "grupo audiorama comunicaciones"
    ],
    "usa": [
      "usa"
    ],
    "hip hop": [
      "hip hop"
    ],
    "música urbana": [
      "música urbana"
    ],
    "banda tradicional": [
      "banda tradicional"
    ],
    "r&b": [
      "r&b"
    ],
    "religious": [
      "religious"
    ],
    "noticias opinion": [
      "noticias opinion"
    ],
    "public": [
      "public"
    ],
    "various music": [
      "various music"
    ],
    "charts": [
      "charts"
    ],
    "clásicos en español": [
      "clásicos en español"
    ],
    "romantic music": [
      "romantic music"
    ],
    "salsa": [
      "salsa"
    ],
    "soft rock": [
      "soft rock"
    ],
    "chill": [
      "chill"
    ],
    "classic": [
      "classic"
    ],
    "reggaeton": [
      "reggaeton"
    ],
    "indie rock": [
      "indie rock"
    ],
    "relax": [
      "relax"
    ],
    "news talk music": [
      "news talk music"
    ],
    "ciudad de mexico": [
      "ciudad de mexico"
    ],
    "cumbia": [
      "cumbia"
    ],
    "guadalajara": [
      "guadalajara"
    ],
    "deportes": [
      "deportes"
    ],
    "00s": [
      "00s"
    ],
    "electronica": [
      "electronica"
    ],
    "norteño": [
      "norteño"
    ],
    "variety hits": [
      "variety hits"
    ],
    "en todas partes": [
      "en todas partes"
    ],
    "70er": [
      "70er"
    ],
    "pop latino": [
      "pop latino"
    ],
    "baja california": [
      "baja california"
    ],
    "eurodance": [
      "eurodance"
    ],
    "rnb": [
      "rnb"
    ],
    "acir online": [
      "acir online"
    ],
    "gospel": [
      "gospel"
    ],
    "música romántica": [
      "música romántica"
    ],
    "features": [
      "features"
    ],
    "latinoamerica": [
      "latinoamerica"
    ],
    "coahuila": [
      "coahuila"
    ],
    "club": [
      "club"
    ],
    "weather": [
      "weather"
    ],
    "local talk": [
      "local talk"
    ],
    "local information": [
      "local information"
    ],
    "norteña": [
      "norteña"
    ],
    "latin": [
      "latin"
    ],
    "electronic dance music": [
      "electronic dance music"
    ],
    "balada romántica": [
      "balada romántica"
    ],
    "grupo radio centro": [
      "grupo radio centro"
    ],
    "información": [
      "información"
    ],
    "gdl": [
      "gdl"
    ],
    "otr": [
      "otr"
    ],
    "70's": [
      "70's"
    ],
    "ciudad mexico": [
      "ciudad mexico"
    ],
    "mix": [
      "mix"
    ],
    "big band": [
      "big band"
    ],
    "downtempo": [
      "downtempo"
    ],
    "punk": [
      "punk"
    ],
    "michoacán": [
      "michoacán"
    ],
    "latino américa": [
      "latino américa"
    ],
    "contemporary": [
      "contemporary"
    ],
    "sport": [
      "sport"
    ],
    "dj remix": [
      "dj remix"
    ],
    "1980s": [
      "1980s"
    ],
    "romantica": [
      "romantica"
    ],
    "latino": [
      "latino"
    ],
    "spanish adult hits": [
      "spanish adult hits"
    ],
    "heavy metal": [
      "heavy metal"
    ],
    "ranchera": [
      "ranchera"
    ],
    "talk & speech": [
      "talk & speech"
    ],
    "talk show": [
      "talk show"
    ],
    "aguascalientes": [
      "aguascalientes"
    ],
    "guanajuato": [
      "guanajuato"
    ],
    "community": [
      "community"
    ],
    "sonora": [
      "sonora"
    ],
    "university": [
      "university"
    ],
    "spanish contemporary hits": [
      "spanish contemporary hits"
    ],
    "christmas": [
      "christmas"
    ],
    "orf": [
      "orf"
    ],
    "tropical music": [
      "tropical music"
    ],
    "instrumental": [
      "instrumental"
    ],
    "sports news": [
      "sports news"
    ],
    "60er": [
      "60er"
    ],
    "multicultural": [
      "multicultural"
    ],
    "entertainment": [
      "entertainment"
    ],
    "música tropical": [
      "música tropical"
    ],
    "student radio": [
      "student radio"
    ],
    "sinaloa": [
      "sinaloa"
    ],
    "misc": [
      "misc"
    ],
    "1990s": [
      "1990s"
    ],
    "cultura": [
      "cultura"
    ],
    "radio fórmula": [
      "radio fórmula"
    ],
    "sports talk": [
      "sports talk"
    ],
    "romance": [
      "romance"
    ],
    "w radio": [
      "w radio"
    ],
    "college": [
      "college"
    ],
    "grupo radio cañón": [
      "grupo radio cañón"
    ],
    "walm": [
      "walm"
    ],
    "old time radio": [
      "old time radio"
    ],
    "dj sets": [
      "dj sets"
    ],
    "dance music": [
      "dance music"
    ],
    "mixed": [
      "mixed"
    ],
    "the best of 80's": [
      "the best of 80's"
    ],
    "sertanejo": [
      "sertanejo"
    ],
    "estado de méxico": [
      "estado de méxico"
    ],
    "la mejor": [
      "la mejor"
    ],
    "la mejor aquí nomás": [
      "la mejor aquí nomás"
    ],
    "la mejor fm": [
      "la mejor fm"
    ],
    "noticias y deportes": [
      "noticias y deportes"
    ],
    "christian music": [
      "christian music"
    ],
    "chillout+lounge": [
      "chillout+lounge"
    ],
    "dj": [
      "dj"
    ],
    "dj mixes": [
      "dj mixes"
    ],
    "new wave": [
      "new wave"
    ],
    "24/7": [
      "24/7"
    ],
    "informativa": [
      "informativa"
    ],
    "aquí nomás": [
      "aquí nomás"
    ],
    "yucatán": [
      "yucatán"
    ],
    "hd": [
      "hd"
    ],
    "relaxation": [
      "relaxation"
    ],
    "club dance": [
      "club dance"
    ],
    "2010s": [
      "2010s"
    ],
    "popular": [
      "popular"
    ],
    "clasicos": [
      "clasicos"
    ],
    "la lupe": [
      "la lupe"
    ],
    "experimental": [
      "experimental"
    ],
    "tamaulipas": [
      "tamaulipas"
    ],
    "campus radio": [
      "campus radio"
    ],
    "ntr medios de comunicación": [
      "ntr medios de comunicación"
    ],
    "radio universitaria": [
      "radio universitaria"
    ],
    "paradise": [
      "paradise"
    ],
    "rock en español": [
      "rock en español"
    ],
    "80s en español": [
      "80s en español"
    ],
    "internet radio": [
      "internet radio"
    ],
    "rancheras": [
      "rancheras"
    ],
    "deporte": [
      "deporte"
    ],
    "variado": [
      "variado"
    ],
    "los40": [
      "los40"
    ],
    "grupo radiofónico zer": [
      "grupo radiofónico zer"
    ],
    "variada": [
      "variada"
    ],
    "swing": [
      "swing"
    ],
    "new classics": [
      "new classics"
    ],
    "rock classics": [
      "rock classics"
    ],
    "islam": [
      "islam"
    ],
    "islamic": [
      "islamic"
    ],
    "cultural news": [
      "cultural news"
    ],
    "musica clasica romantica": [
      "musica clasica romantica"
    ],
    "volksmusik": [
      "volksmusik"
    ],
    "imer": [
      "imer"
    ],
    "mérida": [
      "mérida"
    ],
    "@fm": [
      "@fm"
    ],
    "@fm te conecta": [
      "@fm te conecta"
    ],
    "arroba fm": [
      "arroba fm"
    ],
    "arroba fm te conecta": [
      "arroba fm te conecta"
    ],
    "texas": [
      "texas"
    ],
    "party": [
      "party"
    ],
    "lounge music": [
      "lounge music"
    ],
    "klassik": [
      "klassik"
    ],
    "clasicos en ingles": [
      "clasicos en ingles"
    ],
    "grupo fórmula": [
      "grupo fórmula"
    ],
    "puebla": [
      "puebla"
    ],
    "te conecta": [
      "te conecta"
    ],
    "zacatecas": [
      "zacatecas"
    ],
    "tech house": [
      "tech house"
    ],
    "smooth": [
      "smooth"
    ],
    "dancehall": [
      "dancehall"
    ],
    "relaxing": [
      "relaxing"
    ],
    "live sports": [
      "live sports"
    ],
    "progressive rock": [
      "progressive rock"
    ],
    "boca del río": [
      "boca del río"
    ],
    "dub": [
      "dub"
    ],
    "christmas music": [
      "christmas music"
    ],
    "70 80 hits": [
      "70 80 hits"
    ],
    "cadena rasa": [
      "cadena rasa"
    ],
    "electropop": [
      "electropop"
    ],
    "1980's": [
      "1980's"
    ],
    "veracruz city": [
      "veracruz city"
    ],
    "mpb": [
      "mpb"
    ],
    "entrevistas": [
      "entrevistas"
    ],
    "instituto mexicano de la radio": [
      "instituto mexicano de la radio"
    ],
    "musica popular": [
      "musica popular"
    ],
    "retro hits": [
      "retro hits"
    ],
    "npr": [
      "npr"
    ],
    "concesión social": [
      "concesión social"
    ],
    "weihnachten": [
      "weihnachten"
    ],
    "radio publique": [
      "radio publique"
    ],
    "variedad": [
      "variedad"
    ],
    "radio universidad": [
      "radio universidad"
    ],
    "indigenous": [
      "indigenous"
    ],
    "orchestral": [
      "orchestral"
    ],
    "comedy": [
      "comedy"
    ],
    "soulful house": [
      "soulful house"
    ],
    "vrt": [
      "vrt"
    ],
    "world news": [
      "world news"
    ],
    "electro house": [
      "electro house"
    ],
    "religion": [
      "religion"
    ],
    "drum and bass": [
      "drum and bass"
    ],
    "dnb": [
      "dnb"
    ],
    "dubstep": [
      "dubstep"
    ],
    "social": [
      "social"
    ],
    "cumbias": [
      "cumbias"
    ],
    "oldies 50's/60's": [
      "oldies 50's/60's"
    ],
    "rock 'n' roll": [
      "rock 'n' roll"
    ],
    "radio fórmula primera cadena": [
      "radio fórmula primera cadena"
    ]
  }
};
