import { json, type LoaderFunctionArgs } from "@remix-run/node";
import type { AiRecommendationResponse, DescriptorStation, WorldMoodDescriptor } from "~/types/ai";

const BASE_STATIONS: Record<string, DescriptorStation[]> = {
  "aurora-trails": [
    {
      uuid: "aurora-horizon-1",
      name: "Reykjavik Aurora FM",
      url: "https://streams.radio-passport.com/aurora",
      streamUrl: "https://streams.radio-passport.com/aurora",
      favicon: "/radio-passport-icon.png",
      country: "Iceland",
      countryCode: "IS",
      state: null,
      language: "Icelandic",
      languageCodes: ["is"],
      tags: "ambient,chill,northern lights",
      tagList: ["ambient", "chill", "northern lights"],
      bitrate: 192,
      codec: "mp3",
      homepage: "https://aurorafm.example.com",
      hls: false,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Glacial pads and aurora-inspired textures drifting above Reykjavik.",
    },
    {
      uuid: "aurora-horizon-2",
      name: "Oslo Fjord Echoes",
      url: "https://streams.radio-passport.com/fjord",
      streamUrl: "https://streams.radio-passport.com/fjord",
      favicon: "/radio-passport-icon.png",
      country: "Norway",
      countryCode: "NO",
      state: null,
      language: "Norwegian",
      languageCodes: ["no"],
      tags: "downtempo,scandinavian",
      tagList: ["downtempo", "scandinavian"],
      bitrate: 160,
      codec: "aac",
      homepage: "https://fjordechoes.example.com",
      hls: true,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Nordic downtempo with soft shoreline field recordings.",
    },
    {
      uuid: "aurora-horizon-3",
      name: "Svalbard Signal",
      url: "https://streams.radio-passport.com/svalbard",
      streamUrl: "https://streams.radio-passport.com/svalbard",
      favicon: "/radio-passport-icon.png",
      country: "Norway",
      countryCode: "NO",
      state: "Svalbard",
      language: "English",
      languageCodes: ["en"],
      tags: "arctic,ambient",
      tagList: ["arctic", "ambient"],
      bitrate: 128,
      codec: "mp3",
      homepage: "https://svalbard-signal.example.com",
      hls: false,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Slow-blooming drones captured beneath polar twilight.",
    },
    {
      uuid: "aurora-horizon-4",
      name: "Helsinki Polar Jazz",
      url: "https://streams.radio-passport.com/polarjazz",
      streamUrl: "https://streams.radio-passport.com/polarjazz",
      favicon: "/radio-passport-icon.png",
      country: "Finland",
      countryCode: "FI",
      state: null,
      language: "Finnish",
      languageCodes: ["fi"],
      tags: "jazz,night",
      tagList: ["jazz", "night"],
      bitrate: 192,
      codec: "mp3",
      homepage: "https://polarnightjazz.example.com",
      hls: false,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Late-night Nordic jazz with frosted brass and vinyl crackle.",
    },
  ],
  "desert-nocturne": [
    {
      uuid: "desert-night-1",
      name: "Marrakesh Midnight Market",
      url: "https://streams.radio-passport.com/marrakesh",
      streamUrl: "https://streams.radio-passport.com/marrakesh",
      favicon: "/radio-passport-icon.png",
      country: "Morocco",
      countryCode: "MA",
      state: null,
      language: "Arabic",
      languageCodes: ["ar"],
      tags: "gnawa,desert",
      tagList: ["gnawa", "desert"],
      bitrate: 160,
      codec: "aac",
      homepage: "https://midnightmarket.example.com",
      hls: true,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Gnawa rhythms weaving through the echo of lantern-lit souks.",
    },
    {
      uuid: "desert-night-2",
      name: "Cairo Rooftop Breeze",
      url: "https://streams.radio-passport.com/cairo",
      streamUrl: "https://streams.radio-passport.com/cairo",
      favicon: "/radio-passport-icon.png",
      country: "Egypt",
      countryCode: "EG",
      state: null,
      language: "Arabic",
      languageCodes: ["ar"],
      tags: "lounge,oriental",
      tagList: ["lounge", "oriental"],
      bitrate: 128,
      codec: "mp3",
      homepage: "https://cairorooftop.example.com",
      hls: false,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Midnight oud sessions drifting over warm city air.",
    },
    {
      uuid: "desert-night-3",
      name: "Doha Mirage Lounge",
      url: "https://streams.radio-passport.com/doha",
      streamUrl: "https://streams.radio-passport.com/doha",
      favicon: "/radio-passport-icon.png",
      country: "Qatar",
      countryCode: "QA",
      state: null,
      language: "Arabic",
      languageCodes: ["ar"],
      tags: "chillout,night",
      tagList: ["chillout", "night"],
      bitrate: 192,
      codec: "mp3",
      homepage: "https://dohamirage.example.com",
      hls: false,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Desert breeze lounge with low-slung bass and oud flourishes.",
    },
    {
      uuid: "desert-night-4",
      name: "Riyadh Night Caravan",
      url: "https://streams.radio-passport.com/riyadh",
      streamUrl: "https://streams.radio-passport.com/riyadh",
      favicon: "/radio-passport-icon.png",
      country: "Saudi Arabia",
      countryCode: "SA",
      state: null,
      language: "Arabic",
      languageCodes: ["ar"],
      tags: "electronic,desert",
      tagList: ["electronic", "desert"],
      bitrate: 160,
      codec: "aac",
      homepage: "https://nightcaravan.example.com",
      hls: true,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Desert electronica with distant caravan percussion.",
    },
  ],
  "harbor-dawn": [
    {
      uuid: "harbor-dawn-1",
      name: "Lisbon Harbor Daybreak",
      url: "https://streams.radio-passport.com/lisbon",
      streamUrl: "https://streams.radio-passport.com/lisbon",
      favicon: "/radio-passport-icon.png",
      country: "Portugal",
      countryCode: "PT",
      state: null,
      language: "Portuguese",
      languageCodes: ["pt"],
      tags: "bossa nova,sunrise",
      tagList: ["bossa nova", "sunrise"],
      bitrate: 160,
      codec: "aac",
      homepage: "https://harbordaybreak.example.com",
      hls: true,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Sun-warmed bossa nova echoing from Alfama balconies.",
    },
    {
      uuid: "harbor-dawn-2",
      name: "Cape Town Morning Currents",
      url: "https://streams.radio-passport.com/capetown",
      streamUrl: "https://streams.radio-passport.com/capetown",
      favicon: "/radio-passport-icon.png",
      country: "South Africa",
      countryCode: "ZA",
      state: null,
      language: "English",
      languageCodes: ["en"],
      tags: "afro-jazz,sunrise",
      tagList: ["afro-jazz", "sunrise"],
      bitrate: 192,
      codec: "mp3",
      homepage: "https://morningcurrents.example.com",
      hls: false,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Afro-jazz sunrise sets with gulls and harbor bells.",
    },
    {
      uuid: "harbor-dawn-3",
      name: "Hong Kong Harbor Haze",
      url: "https://streams.radio-passport.com/hongkong",
      streamUrl: "https://streams.radio-passport.com/hongkong",
      favicon: "/radio-passport-icon.png",
      country: "Hong Kong",
      countryCode: "HK",
      state: null,
      language: "Cantonese",
      languageCodes: ["yue"],
      tags: "city pop,morning",
      tagList: ["city pop", "morning"],
      bitrate: 160,
      codec: "aac",
      homepage: "https://harborhaze.example.com",
      hls: true,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Soft city pop with ferry horn interludes at dawn.",
    },
    {
      uuid: "harbor-dawn-4",
      name: "Seattle Mist Radio",
      url: "https://streams.radio-passport.com/seattle",
      streamUrl: "https://streams.radio-passport.com/seattle",
      favicon: "/radio-passport-icon.png",
      country: "United States",
      countryCode: "US",
      state: "Washington",
      language: "English",
      languageCodes: ["en"],
      tags: "indie,coffeehouse",
      tagList: ["indie", "coffeehouse"],
      bitrate: 192,
      codec: "mp3",
      homepage: "https://seattlemist.example.com",
      hls: false,
      lastCheckOk: true,
      lastCheckOkTime: null,
      lastCheckTime: null,
      lastLocalCheckTime: null,
      sslError: false,
      votes: 0,
      clickCount: 0,
      clickTrend: 0,
      highlight: "Coffeehouse indie with rain-soaked vinyl textures.",
    },
  ],
};

const DESCRIPTORS: Array<Omit<WorldMoodDescriptor, "generatedAt">> = [
  {
    id: "descriptor-aurora-trails",
    slug: "aurora-trails",
    label: "Aurora Trails",
    mood: "Luminous & Serene",
    summary: "Arctic calm washed in shimmering synths and radio snow.",
    narrative:
      "Follow the aurora from Reykjavik to Helsinki with stations that glow like polar dawn, blending ambient pads, jazz, and midnight field recordings.",
    theme: {
      palette: {
        background: "#04091f",
        accent: "#6cc7ff",
        glow: "#aee6ff",
      },
      camera: {
        latitude: 64.1466,
        longitude: -21.9426,
        altitude: 1.8,
      },
    },
    playback: {
      strategy: "autoplay-first",
      crossfadeSeconds: 12,
    },
    stations: BASE_STATIONS["aurora-trails"]!,
  },
  {
    id: "descriptor-desert-nocturne",
    slug: "desert-nocturne",
    label: "Desert Nocturne",
    mood: "Velvet Twilight",
    summary: "Warm desert winds with hypnotic midnight grooves.",
    narrative:
      "Glide between Marrakesh rooftops and Doha lounges as oud, electronic pulses, and lantern-lit percussion guide you through the hush of desert midnight.",
    theme: {
      palette: {
        background: "#2b0f19",
        accent: "#f7a35c",
        glow: "#ffd7a3",
      },
      camera: {
        latitude: 31.6295,
        longitude: -7.9811,
        altitude: 1.2,
      },
    },
    playback: {
      strategy: "respect-current",
      crossfadeSeconds: 8,
    },
    stations: BASE_STATIONS["desert-nocturne"]!,
  },
  {
    id: "descriptor-harbor-dawn",
    slug: "harbor-dawn",
    label: "Harbor Dawn",
    mood: "Optimistic & Breezy",
    summary: "Coastal mornings steeped in jazz, city pop, and salt air.",
    narrative:
      "From Lisbon's tiled hills to Hong Kong's ferries, greet the sunrise with breezy rhythms, gulls in the distance, and coffeehouse warmth.",
    theme: {
      palette: {
        background: "#041421",
        accent: "#f5d98c",
        glow: "#ffefc1",
      },
      camera: {
        latitude: 38.7223,
        longitude: -9.1393,
        altitude: 1.5,
      },
    },
    playback: {
      strategy: "autoplay-first",
      crossfadeSeconds: 6,
    },
    stations: BASE_STATIONS["harbor-dawn"]!,
  },
];

function pickDescriptor(slug: string | null): Omit<WorldMoodDescriptor, "generatedAt"> {
  const normalized = slug?.toLowerCase() ?? null;
  const pool = normalized
    ? DESCRIPTORS.filter((descriptor) =>
        descriptor.slug === normalized || descriptor.mood.toLowerCase().includes(normalized),
      )
    : DESCRIPTORS;

  const candidates = pool.length > 0 ? pool : DESCRIPTORS;
  const randomIndex = Math.floor(Math.random() * candidates.length);
  return candidates[randomIndex] ?? DESCRIPTORS[0]!;
}

export async function loader({ request }: LoaderFunctionArgs) {
  const url = new URL(request.url);
  const moodParam = url.searchParams.get("mood");
  const selected = pickDescriptor(moodParam);

  const descriptor: WorldMoodDescriptor = {
    ...selected,
    stations: selected.stations,
    generatedAt: new Date().toISOString(),
  };

  const payload: AiRecommendationResponse = { descriptor };
  return json(payload, {
    headers: {
      "Cache-Control": "no-store",
    },
  });
}
